### ISSUE TITLE
Compiling Eigen 3.3.4 too slow

### ISSUE THREAD

**Issue by jiec-msft** [FeeZhu/ICP#5]
作者你好，请问你的Eigen3.3.4是怎么安装的呀？我这边自己从源代码编译，都已经编译了6个小时了，还没有结束。在线等，挺急的。

**Comment by FeeZhu** [comment]
As i know, Eigen library  does not need  to be compiled. You can download the zip file from the official website and  including it into your project. If you still have a problem, i can upload my files soon.

**Comment by jiec-msft** [comment]
I hope that you can upload you files, thank you!

**Comment by FeeZhu** [comment]
> I hope that you can upload you files, thank you!

https://github.com/FeeZhu/Eigen3

**Comment by jiec-msft** [comment]
got it!
